#Logger module
CONFIG_LOG=y

#Bluetooth LE
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Projekt_studia_indywidualne"
CONFIG_BT_MAX_CONNS=1

#Button and LED library
CONFIG_DK_LIBRARY=y 

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048